#!/bin/bash

set -ex

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp $TMPDIR/concoure-curl-resource-request.XXXXXX)

cat > $payload <&0

url=$(jq -r '.source.url // ""' < $payload)
username=$(jq -r '.source.username // ""' < $payload)
password=$(jq -r '.source.password // ""' < $payload)
skip_ssl_verification=$(jq -r '.source.skip_ssl_verification // ""' < $payload)

if [ -z "$url" ]; then
  echo "invalid payload (missing url)"
  exit 1
fi

args_security=

[ -n "$username" ] && args_security="-u $username";
[ -n "$username" ] && [ -n "$password" ] && args_security="$args_security:$password";
trueValue="true"
[ -n "$skip_ssl_verification" ] && [ "${skip_ssl_verification,,}" = "${trueValue,,}" ] && args_security="$args_security -k";

final_url="$args_security $url"

echo "{\"version\":\"$final_url\"}" | jq --slurp . >&3
